### ISSUE TITLE
Series element retrieval

### ISSUE THREAD

**Issue by 2Cubed** [DarthTorus/Formu-bot#10]
Ability to get the `n`th element of some popular series.

- [x] Fibonacci
- [x] Squares, cubes
- [x] Collatz
- [x] Lucas numbers
- [x] Triangle numbers
etc.

```
>>>series cube 2
8

>>>series triangle 4
10
```

**Comment by DarthTorus** [comment]
OOOOO. I **LOVE** Fibonacci 😸 💚

**Comment by DarthTorus** [comment]
Closed by using `>>>calc n^y`
